server: 
  port: 8888

web:
  resource-path: D:/Project/Company/Dreamer-cms-java/src/main/resources/dreamer-cms/

spring:
  datasource: 
    name: dev
    url: jdbc:mysql://192.168.31.11:33060/dreamer-cms?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000
    database: 0
    password:
    jedis:
      pool:
        max-idle: 100
        min-idle: 50
        max-wait: -1

# 日志配置
logging:
  path: D:/dreamer-cms/logs/
  level:
    root: info              